echo off
SET HOME=D:\PROJECT\CRYPTOSRC\IPST-100-TOOLKIT
SET SRCBASE=%HOME%\SRC
SET SRCDIR=%HOME%\Release\x64
SET SRCDIR_x86=%HOME%\Release\x86
SET DLLNAME=lib.ipst100.server.level*.dll

SET TARGETDIR=D:\PROJECT\CRYPTOSRC\IPST-100-TOOLKIT\bin\Release
SET TARGETDIR2=D:\PROJECT\IPST-100 TOOLKIT ¡¶¿€\RELEASE

SET LINUX_BIN_DIR=Z:\IPST-100-TOOLKIT\IPST-100-TOOLKIT\bin\gnu
SET LINUX_LIB_DIR=Z:\IPST-100-TOOLKIT\lib\gnu


SET MIDREL=SERVER\C#

SET SRCDLLDIR=D:\PROJECT\CRYPTOSRC\BASE\dll
SET OUTFILE=%HOME%\out.txt
SET MSSOL=%HOME%\IPST-100-TOOLKIT_2008.sln
SET BUILDLOG=%HOME%\lsa\x64\Release\lsa.log

